version: "3.8"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: innova
        container_name: innova-dev
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - app_net

    nginx:
        image: nginx:alpine
        container_name: innova-nginx-dev
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx-dev:/etc/nginx/conf.d/
        networks:
            - app_net

networks:
    app_net:
        external: true
